# Generated by Django 3.2.3 on 2021-06-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_auto_20210604_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiariodireccion',
            name='descripcion_ubicacion',
            field=models.TextField(blank=True, verbose_name='Referencias de la ubicación'),
        ),
    ]
