# Generated by Django 3.2.3 on 2021-06-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20210614_2038'),
        ('beneficiarios', '0005_auto_20210623_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiariodireccion',
            name='asentamiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalogos.asentamiento', verbose_name='Asentamiento'),
        ),
        migrations.AlterField(
            model_name='beneficiariodireccion',
            name='localidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalogos.localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='beneficiariodireccion',
            name='municipio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalogos.municipio', verbose_name='Municipio'),
        ),
    ]
