# Generated by Django 3.2.3 on 2021-08-27 00:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0005_auto_20210824_2332'),
        ('catalogos', '0002_auto_20210614_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefensoriaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(default='', max_length=18, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP')),
                ('tramite_realizar', models.CharField(default='', max_length=80, verbose_name='Trámite a Realizar')),
                ('fecha', models.DateField(verbose_name='Fecha de trámite')),
                ('num_telefonico', models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(\\d{10})$')], verbose_name='Número de teléfono')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Correo electrónico')),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.localidad', verbose_name='Localidad')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
    ]
