# Generated by Django 3.2.3 on 2021-08-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defensoria_publica', '0002_alter_defensoriapublica_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensoriapublica',
            name='fecha',
        ),
    ]
