# Generated by Django 3.2.3 on 2021-08-26 08:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0005_auto_20210824_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandamientosJudiciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(default='', max_length=18, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP')),
                ('acta_nac_original', models.BooleanField(default=False, verbose_name='Acta de Nacimiento Original')),
                ('curp_act', models.BooleanField(default=False, verbose_name='CURP Actualizada')),
                ('comprobante_domicilio', models.BooleanField(default=False, verbose_name='Comprobante domicilio')),
                ('pasaporte_vigente', models.BooleanField(default=False, verbose_name='Pasaporte vigente')),
                ('matricula_consular', models.BooleanField(default=False, verbose_name='Matrícula Consular')),
                ('pago_en_caja_fiscalia', models.BooleanField(default=False, verbose_name='Pago que se realiza en caja de fiscalia')),
                ('fotografia', models.BooleanField(default=False, verbose_name='Fotografía tamaño infantil blanco y negro con fondo blanco')),
                ('ine_familiar', models.BooleanField(default=False, verbose_name='INE del familiar directo que va a tramitar el documento')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
    ]
