# Generated by Django 3.2.3 on 2021-08-26 00:43

from django.db import migrations, models
import django.db.models.deletion
import traslado_cuerpos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_rename_contraseña_empleado_contra'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionMigratoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(max_length=20, verbose_name='Situación Migratoria')),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoCuerpo',
            fields=[
                ('folio', models.IntegerField(default=traslado_cuerpos.models.autoincremento_folio, primary_key=True, serialize=False, verbose_name='folio')),
                ('nombre_fallecido', models.CharField(max_length=70, verbose_name='Nombre del fallecido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_deceso', models.DateField(verbose_name='Fecha de deceso')),
                ('causa_muerte', models.CharField(max_length=50, verbose_name='Causa de la muerte')),
                ('lugar_deceso', models.CharField(max_length=40, verbose_name='Lugar del deceso')),
                ('lugar_origen', models.CharField(max_length=40, verbose_name='Lugar de origen')),
                ('anios_en_eu', models.PositiveIntegerField(default=0, verbose_name='Años')),
                ('meses_en_eu', models.PositiveIntegerField(default=0, verbose_name='Meses')),
                ('nombre_familiar_mexicano', models.CharField(max_length=70, verbose_name='Nombre del familiar en México')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado', verbose_name='Empleado')),
                ('situacion_migratoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traslado_cuerpos.situacionmigratoria', verbose_name='Situación Migratoria')),
            ],
        ),
    ]
