# Generated by Django 3.2.3 on 2021-08-27 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado_cuerpos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasladocuerpo',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('\\+(9[976]\\d|8[987530]\\d|6[987]\\d|5[90]\\d|42\\d|3[875]\\d|2[98654321]\\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)\\d{1,14}$')], verbose_name='Teléfono'),
        ),
    ]
