# Generated by Django 3.2.3 on 2021-06-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='contra',
        ),
    ]
