# Generated by Django 3.2.3 on 2021-08-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion_personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadesaparecida',
            name='direccion_desaparecido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
    ]
