# Generated by Django 3.2.3 on 2021-08-26 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencia_conducir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciaconducir',
            name='tipo_sangre',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^(A|B|AB|O)[-+]$')], verbose_name='Tipo de Sangre'),
        ),
    ]
