# Generated by Django 3.2.3 on 2021-08-25 22:31

from django.db import migrations, models
import django.db.models.deletion
import visas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_rename_contraseña_empleado_contra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('folio', models.IntegerField(default=visas.models.autoincremento_folio, primary_key=True, serialize=False, verbose_name='folio')),
                ('nombre_solicitante', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno_solicitante', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno_solicitante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('pasaporte', models.BooleanField(default=False, verbose_name='Pasaporte')),
                ('direccion_usa', models.CharField(max_length=70, verbose_name='Dirección de Estados Unidos')),
                ('persona_visitar', models.CharField(max_length=70, verbose_name='Nombre de la persona a visitar')),
                ('tel_persona_visitar', models.CharField(max_length=10, verbose_name='Teléfono de la persona a visitar')),
                ('fe_nacimiento_madre', models.DateField(verbose_name='Fecha de nacimiento de la madre')),
                ('fe_nacimiento_padre', models.DateField(verbose_name='Fecha de nacimiento del padre')),
                ('dir_trabajo_escuela', models.CharField(max_length=80, verbose_name='Dirección del lugar de trabajo o escuela')),
                ('nom_dir_trabajo_escuela', models.CharField(max_length=35, verbose_name='Nombre de la dirección del trabajo o escuela')),
                ('fe_ingreso_trabajo_escuela', models.DateField(verbose_name='Fecha de ingreso al trabajo o escuela')),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingreso Mensual')),
                ('fecha_viaje', models.DateField(verbose_name='Fecha tentativa de viaje')),
                ('red_social_uno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Red social 1')),
                ('usuario_uno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de usuario')),
                ('red_social_dos', models.CharField(blank=True, max_length=30, null=True, verbose_name='Red social 2')),
                ('usuario_dos', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de usuario')),
                ('red_social_tres', models.CharField(blank=True, max_length=30, null=True, verbose_name='Red social 3')),
                ('usuario_tres', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de usuario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('pago', models.BooleanField(default=False)),
                ('fecha_cita', models.DateField(blank=True, null=True, verbose_name='Fecha de la cita en el consulado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
