# Generated by Django 3.2.3 on 2021-09-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corazon_plata', '0007_corazonplata_datos_completos'),
        ('visas', '0002_alter_visa_tel_persona_visitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='corazon_plata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corazon_plata.corazonplata', verbose_name='Trámite de Corazón de Plata'),
        ),
    ]
