# Generated by Django 3.2.3 on 2021-09-09 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0003_visa_corazon_plata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='apellido_paterno_solicitante',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='dir_trabajo_escuela',
            field=models.CharField(max_length=80, null=True, verbose_name='Dirección del lugar de trabajo o escuela'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='direccion_usa',
            field=models.CharField(max_length=70, null=True, verbose_name='Dirección de Estados Unidos'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='fe_ingreso_trabajo_escuela',
            field=models.DateField(null=True, verbose_name='Fecha de ingreso al trabajo o escuela'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='fe_nacimiento_madre',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento de la madre'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='fe_nacimiento_padre',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento del padre'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='fecha_viaje',
            field=models.DateField(null=True, verbose_name='Fecha tentativa de viaje'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso Mensual'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='nom_dir_trabajo_escuela',
            field=models.CharField(max_length=35, null=True, verbose_name='Nombre de la dirección del trabajo o escuela'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='nombre_solicitante',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='persona_visitar',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombre de la persona a visitar'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='tel_persona_visitar',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('\\+(9[976]\\d|8[987530]\\d|6[987]\\d|5[90]\\d|42\\d|3[875]\\d|2[98654321]\\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)\\d{1,14}$')], verbose_name='Teléfono de la persona a visitar'),
        ),
    ]
