# Generated by Django 3.2.3 on 2021-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20210614_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='localidad',
            field=models.CharField(max_length=100, verbose_name='Localidad'),
        ),
    ]
