# Generated by Django 3.2.3 on 2021-07-20 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0004_auto_20210625_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorazonPlata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(default='', max_length=18, validators=[django.core.validators.RegexValidator('([A-Z]{4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[A-Z]{3}[0-9A-Z]\\d)')], verbose_name='CURP')),
                ('firmo_recibo', models.BooleanField(default=False, verbose_name='Firmó recibo')),
                ('emitio_factura', models.BooleanField(default=False, verbose_name='Emitió factura')),
                ('curp_representante', models.BooleanField(default=False, verbose_name='CURP del representante')),
                ('copia_ine_representante', models.BooleanField(default=False, verbose_name='Copia de la INE del representante')),
                ('copia_cheque', models.BooleanField(default=False, verbose_name='Copia del cheque: ')),
                ('tiene_cuenta_bancaria', models.BooleanField(default=False, verbose_name='Tiene cuenta bancaria')),
                ('titulo_propiedad', models.BooleanField(default=False, verbose_name='Título de propiedad')),
                ('solicitud_apoyo', models.BooleanField(default=False, verbose_name='Solicitud de apoyo')),
                ('es_organizacion', models.BooleanField(default=False, verbose_name='Es organización')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
        ),
    ]
