# Generated by Django 3.2.3 on 2021-08-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corazon_plata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corazonplata',
            name='curp',
        ),
    ]
