# Generated by Django 3.2.3 on 2021-08-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corazon_plata', '0002_remove_corazonplata_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre de la federación')),
            ],
        ),
    ]
