# Generated by Django 3.2.3 on 2021-08-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0005_auto_20210824_2332'),
        ('doble_nacionalidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doblenacionalidad',
            name='tramite_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.estadotramite', verbose_name='Estado trámite'),
        ),
    ]
