# Generated by Django 3.2.3 on 2021-06-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_remove_tramite_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreTramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tramite', models.CharField(max_length=50, verbose_name='Nombre del trámite')),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramites.nombretramites', verbose_name='Tipo de trámite'),
        ),
    ]
