# Generated by Django 3.2.3 on 2021-06-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion_migrantes', '0002_auto_20210607_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionmigrantes',
            name='acta_nacimiento',
            field=models.BooleanField(default=False, verbose_name='Acta de nacimiento'),
        ),
    ]
